apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: springbootapp-deployment
  labels:
    app: springbootapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springbootapp
  template:
    metadata:
      labels:
        app: springbootapp
    spec:
      containers:
      - name: springbootapp
        image: nmsrinivas/springbootapp
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: springbootapp
  labels:
    app: springbootapp
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 30002
  selector:
    app: springbootapp
