apiVersion: v1
kind: Service
metadata:
  name: sampleapp
  labels:
    app: sampleapp
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 30002
  selector:
    app: sampleapp
